Models/Trabajadore.cs
using System;
using System.Collections.Generic;

namespace SisalrilProject.Models;

public partial class Trabajadore
{
    public int IdTrabajador { get; set; }

    public string? TrabajadorNombre { get; set; }

    public decimal? TrabajadorTarifa { get; set; }

    public string? Oficio { get; set; }

    public int? TrabajadorSupervisor { get; set; }

    public virtual ICollection<Asignacione> Asignaciones { get; } = new List<Asignacione>();
}

Controllers/TrabajadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SisalrilProject.Models;

namespace SisalrilProject.Controllers
{
    public class TrabajadoresController : Controller
    {
        private readonly SisalrilTaskContext _context;

        public TrabajadoresController(SisalrilTaskContext context)
        {
            _context = context;
        }

        // GET: Trabajadores
        public async Task<IActionResult> Index(string Buscar)
        {
            var trabajadores = from Trabajadore in _context.Trabajadores select Trabajadore;

            if (!String.IsNullOrEmpty(Buscar))
            {
                trabajadores = trabajadores.Where(s => s.TrabajadorNombre!.Contains(Buscar));
            }
            return View(await trabajadores.ToListAsync());
        }

        // GET: Trabajadores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trabajadores == null)
            {
                return NotFound();
            }

            var trabajadore = await _context.Trabajadores
                .FirstOrDefaultAsync(m => m.IdTrabajador == id);
            if (trabajadore == null)
            {
                return NotFound();
            }

            return View(trabajadore);
        }

        // GET: Trabajadores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trabajadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTrabajador,TrabajadorNombre,TrabajadorTarifa,Oficio,TrabajadorSupervisor")] Trabajadore trabajadore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trabajadore);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trabajadore);
        }

        // GET: Trabajadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trabajadores == null)
            {
                return NotFound();
            }

            var trabajadore = await _context.Trabajadores.FindAsync(id);
            if (trabajadore == null)
            {
                return NotFound();
            }
            return View(trabajadore);
        }

        // POST: Trabajadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTrabajador,TrabajadorNombre,TrabajadorTarifa,Oficio,TrabajadorSupervisor")] Trabajadore trabajadore)
        {
            if (id != trabajadore.IdTrabajador)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trabajadore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrabajadoreExists(trabajadore.IdTrabajador))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trabajadore);
        }

        // GET: Trabajadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trabajadores == null)
            {
                return NotFound();
            }

            var trabajadore = await _context.Trabajadores
                .FirstOrDefaultAsync(m => m.IdTrabajador == id);
            if (trabajadore == null)
            {
                return NotFound();
            }

            return View(trabajadore);
        }

        // POST: Trabajadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trabajadores == null)
            {
                return Problem("Entity set 'SisalrilTaskContext.Trabajadores'  is null.");
            }
            var trabajadore = await _context.Trabajadores.FindAsync(id);
            if (trabajadore != null)
            {
                _context.Trabajadores.Remove(trabajadore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrabajadoreExists(int id)
        {
          return _context.Trabajadores.Any(e => e.IdTrabajador == id);
        }
    }
}

Views/Trabajadores/Create.cshtml
@model SisalrilProject.Models.Trabajadore

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Trabajadores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdTrabajador" class="control-label"></label>
                <input asp-for="IdTrabajador" class="form-control" />
                <span asp-validation-for="IdTrabajador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrabajadorNombre" class="control-label"></label>
                <input asp-for="TrabajadorNombre" class="form-control" />
                <span asp-validation-for="TrabajadorNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrabajadorTarifa" class="control-label"></label>
                <input asp-for="TrabajadorTarifa" class="form-control" />
                <span asp-validation-for="TrabajadorTarifa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oficio" class="control-label"></label>
                <input asp-for="Oficio" class="form-control" />
                <span asp-validation-for="Oficio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrabajadorSupervisor" class="control-label"></label>
                <input asp-for="TrabajadorSupervisor" class="form-control" />
                <span asp-validation-for="TrabajadorSupervisor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /> |
                <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trabajadores/Delete.cshtml
@model SisalrilProject.Models.Trabajadore

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>¿Estás seguro de que quieres eliminar esto?</h3>
<div>
    <h4>Trabajadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrabajadorNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrabajadorNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrabajadorTarifa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrabajadorTarifa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Oficio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Oficio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrabajadorSupervisor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrabajadorSupervisor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdTrabajador" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
    </form>
</div>

Views/Trabajadores/Details.cshtml
@model SisalrilProject.Models.Trabajadore

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Trabajadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrabajadorNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrabajadorNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrabajadorTarifa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrabajadorTarifa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Oficio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Oficio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrabajadorSupervisor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrabajadorSupervisor)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.IdTrabajador">Editar</a> |
    <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
</div>

Views/Trabajadores/Edit.cshtml
@model SisalrilProject.Models.Trabajadore

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Trabajadores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdTrabajador" />
            <div class="form-group">
                <label asp-for="TrabajadorNombre" class="control-label"></label>
                <input asp-for="TrabajadorNombre" class="form-control" />
                <span asp-validation-for="TrabajadorNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrabajadorTarifa" class="control-label"></label>
                <input asp-for="TrabajadorTarifa" class="form-control" />
                <span asp-validation-for="TrabajadorTarifa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oficio" class="control-label"></label>
                <input asp-for="Oficio" class="form-control" />
                <span asp-validation-for="Oficio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrabajadorSupervisor" class="control-label"></label>
                <input asp-for="TrabajadorSupervisor" class="form-control" />
                <span asp-validation-for="TrabajadorSupervisor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                <a asp-action="Index" class="btn btn-primary">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trabajadores/Index.cshtml
@model IEnumerable<SisalrilProject.Models.Trabajadore>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Trabajadores</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear Nuevo</a>
</p>

<form asp-controller="Trabajadores" asp-action="Index">
    <p>
        Buscar: <input type="text" name="Buscar" class="form-text" />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark"/>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdTrabajador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrabajadorNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrabajadorTarifa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Oficio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrabajadorSupervisor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdTrabajador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrabajadorNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrabajadorTarifa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oficio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrabajadorSupervisor)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.IdTrabajador">Editar</a> |
                <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.IdTrabajador">Detalles</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.IdTrabajador">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>